### ISSUE TITLE
`switchboard` address on Move.toml

### ISSUE THREAD

**Issue by nathanramli** [switchboard-xyz/sui#1]
## Issue Description

The `switchboard` address on Move.toml should be set to the original address:
`0xc3c7e6eb7202e9fb0389a2f7542b91cc40e4f7a33c02554fec11c4c92f938ea3`

Otherwise, an error will occur when using this repository as a dependency.
https://github.com/switchboard-xyz/sui/blob/b04d89ebe1d69ecf65c2d6516e20d62acb7bbe37/on_demand/Move.toml#L12

## Solution

```toml
[addresses]
switchboard = "0xc3c7e6eb7202e9fb0389a2f7542b91cc40e4f7a33c02554fec11c4c92f938ea3"
```
